Repository tablelandnetwork/go-tableland, pull requests merged in 2023-01, with the labels that each got.

#430 fix: get schema was not parsing statements with autoincrement
  internal/system/impl/sqlstore_test.go
  pkg/sqlstore/impl/system/store.go
Labels: bug

#440 Healthbot fixes and re-enabling & Docker images updating
  .github/workflows/deploy.yml
  Makefile
  cmd/api/Dockerfile
  cmd/api/Dockerfile.debug
  cmd/healthbot/Dockerfile
  cmd/healthbot/config.go
  cmd/healthbot/main.go
  docker/deployed/docker-compose.observability.yml
  docker/deployed/staging/healthbot/.env_healthbot.example
  docker/deployed/staging/healthbot/config.json
  docker/deployed/testnet/healthbot/.env_healthbot.example
  docker/deployed/testnet/healthbot/config.json
Labels: enhancement, infrastructure

#442 dockerignore: avoid excluding files that are part of the repo
  .dockerignore
Labels: infrastructure

#453 ethclient: use EIP-1559 for gas
  pkg/tables/impl/ethereum/client.go
Labels: enhancement
